#!/bin/bash
# -*- ENCODING: UTF-8 -*-
desarrollo=www/desarrollo/repositorios/
programacion=www/programacion/repositorios/
clear
while :
do
echo "
#----------------------------------------#
#           Git Repo Maker  v1.1         #
#----------------------------------------#
#               @heckctor                #
#----------------------------------------#
"
echo "¿Dónde vas a crear el Repositorio? "
echo "1. Desarrollo"
echo "2. Programación"
echo "3. Salir"

echo -n  "Seleccione una opción [1 - 3]. "
 
read opcion

case $opcion in

1) echo "Vas a crear un Repositorio en Desarrollo.";
cd $desarrollo
read -p "Escribe el nombre del Repositorio: " repositorio
mkdir $repositorio
cd $repositorio
git init --bare
sleep 1s
clear
echo "Se creo el  repositorio "$repositorio"."
echo "La URL para clonar es:"
echo "ssh://direccionssh:puerto/~/www/desarrollo/repositorios/"$repositorio
exit 1;;

2) echo "Vas a crear un Repositorio en Programación";
cd $programacion
read -p "Escribe el nombre del Repositorio: " repositorio
mkdir $repositorio
cd $repositorio
git init --bare
sleep 1s
clear
echo "se creó el  repositorio "$repositorio"."
echo "La URL para clonar es:"
echo "ssh://direccionssh:puerto/~/www/programacion/repositorios/"$repositorio
exit 1;;

3)clear 
echo  "Bye!"

exit 1;;

*) echo " "$opcion" es una opción inválida, teclea el número 1, 2 ó 3";

echo "Presiona cualquier tecla y pulsa ENTER continuar...";

read foo
clear;;

esac

done


